package constants

import play.api.i18n.Messages

trait Constants {
  val ZULU_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ssZ"
  val JSESSIONID = "JSESSIONID"
  val USERNAME = "UserName"
  val USER_ID = "USER_ID"
  val LOC_LABEL = "Loc"
  val PAGE_NUM_PARAM = "page_num"
  val ERROR_USER_NOT_LOGGED_IN = "ERROR_USER_NOT_LOGGED_IN"
  val ERROR_DATA_SESSION_EXPIRED = "Session Expired."

  // START: Header Account Tab Names
  val ACCOUNT_SUMMARY_TAB_NAME = "tab_name_account_summary"
  val ORDER_HISTORY_TAB_NAME = "tab_name_order_history"
  val SHIPPING_ADDRESS_TAB_NAME = "tab_name_shipping_address_book"
  val BILLING_ADDRESS_TAB_NAME = "tab_name_billing_address_book"
  val PAYMENT_TAB_NAME = "tab_name_payment"
  val SAKSFIRST_TAB_NAME = "tab_name_saksfirst"
  val ACCOUNT_SETTINGS_TAB_NAME = "tab_name_account_settings"
  val FAVORITES_TAB_NAME = "tab_name_favorites"
  // END: Header Account Tab Names

  // START: Header Account Tab ID's
  val ACCOUNT_SUMMARY_HEADER_TAB_ID = "accountSummary"
  val ORDER_HISTORY_HEADER_TAB_ID = "orderHistory"
  val SHIPPING_ADRERSS_HEADER_TAB_ID = "shippingAddressBook"
  val BILLING_ADDRESS_HEADER_TAB_ID = "billingAddressBook"
  val PAYMENT_HEADER_TAB_ID = "payment"
  val REWARDS_HEADER_TAB_ID = "rewards"
  val ACCOUNT_SETTINGS_HEADER_TAB_ID = "accountSettings"
  val FAVORITES_HEADER_TAB_ID = "favorites"
  // END: Header Account Tab ID's

  // START: SHARED JSON Keys
  val ACCOUNT_TITLE = "account_title"
  val GLOBAL_MESSAGE_KEY = "global_message"
  val SERVICE_DOWN_KEY = "service_down"
  val TRY_LATER_KEY = "try_later"
  val CANCEL_LINK_KEY = "cancel_link"
  val CANCEL_BUTTON_KEY = "cancel_button"
  val SUBMIT_BUTTON_KEY = "submit_button"
  val DELETE_MSG_LINK_KEY = "delete_button"
  val ADD_NEW_LABEL_MSG_KEY = "add_new_label"
  val ALLOWED_OPRERATION_EDIT_KEY = "edit_enabled"
  val ALLOWED_OPRERATION_DELETE_KEY = "delete_enabled"
  val OPTIONS_KEY = "options"
  val EDIT_LINK_KEY = "edit_link"
  val DELETE_LINK_KEY = "delete_link"
  val FIRST_NAME_LABEL_KEY = "first_name_label"
  val LAST_NAME_LABEL_KEY = "last_name_label"
  val NAME_LABEL_KEY = "name_label"
  val EXPIRATION_DATE_LABEL_KEY = "expiration_date_label"
  val VALIDATION_FIRST_NAME_KEY = "invalid_first_name"
  val VALIDATION_LAST_NAME_KEY = "invalid_last_name"
  val VALIDATION_POSTAL_CODE_KEY = "invalid_postal_code"
  val POSTAL_CODE_LABEL = "postal_code_label"
  // END: SHARED JSON Keys

  // START: DISPLAY MESSAGE, IF FIRST NAME, LAST NAME OR BOTH MISSING IN ACCOUNT
  val BLANK_NAME_ACCOUNT_TITLE = "blank_name_account_title"
  val EDIT_YOUR_PROFILE_TITLE = "edit_your_profile_title"
  val EDIT_YOUR_PROFILE_TEXT = "edit_your_profile_text"
  // END: DISPLAY MESSAGE, IF FIRST NAME, LAST NAME OR BOTH MISSING IN ACCOUNT

  val CONFIRM_NEW_PASSWORD_LABEL_KEY = "confirm_new_password"
  val TITLE_KEY = "title"
  val ACTIVE_TITLE_KEY = "active_title"
  val INACTIVE_TITLE_KEY = "inactive_title"
  val MIGRATED_TITLE_KEY = "migrated_title"
  val SUCCESS_TITLE_KEY = "success_title"
  val EDIT_ACTION_KEY = "edit_action"
  val ACCOUNT_RESOURCE_KEY = "account_resource"
  val EDIT_BUTTON_KEY = "edit_button"
  val ENDPOINT_KEY = "endpoint"

  val MODAL_TITLE_KEY = "modal_title"
  val PASSWORD_INFO_KEY = "password_info"
  val SUBSCRIBED_LABEL_KEY = "subscribed_label"
  val UNSBSCRIBED_LABEL_KEY = "unsubscribed_label"
  val SAKS_EMAIL_PREFR_LABEL_KEY = "saks_opt_status"
  val OFF_FIFTH_EMAIL_PREFR_LABEL_KEY = "off5th_opt_status"
  val SAKS_CANADA_EMAIL_PREFR_LABEL_KEY = "saks_canada_opt_status"
  val OFF_FIFTH_CANADA_EMAIL_PREFR_LABEL_KEY = "off5th_canada_opt_status"

  val REQUIRED_FIELD_ERROR_KEY = "required_field_error"
  val INVALID_EMAIL_ERROR_KEY = "invalid_email_error"
  val INVALID_CREDENTIALS_ERROR_KEY = "invalid_credentials_error"
  val SIGN_IN_BUTTON_KEY = "sign_in_button"
  val SIGN_IN_ACTION_KEY = "sign_in_action"
  val FORGOT_PASSWORD_LINK_KEY = "forgot_password_link"
  val FORGOT_PASSWORD_ACTION_KEY = "forgot_password_action"
  val RESET_PASSWORD_ACTION_KEY = "reset_password_action"

  val CONTINUE_BUTTON_LABEL_KEY = "continue_button"
  val BACK_TO_SIGN_IN_LINK_KEY = "back_to_sign_in_link"
  val ACTIVE_FORGOT_PASSWORD_MESSAGE_KEY = "active_forgot_password_message"
  val INACTIVE_FORGOT_PASSWORD_MESSAGE_KEY = "inactive_forgot_password_message"
  val MIGRATED_FORGOT_PASSWORD_MESSAGE_KEY = "migrated_forgot_password_message"

  val NEW_PASSWORD_LABEL_KEY = "new_password_label"
  val CONFIRM_PASSWORD_LABEL_KEY = "confirm_password_label"
  val REQUIRED_FIELD_LABEL_KEY = "required_field"
  val INVALID_EQUAL_PASSWORD_KEY = "invalid_equal_password"
  val INVALID_PASSWORD_LABEL_KEY = "invalid_password"
  val RESET_PASSWORD_LABEL_KEY = "reset_password_message"
  val SUCCESS_RESET_PASSWORD_MESSAGE_KEY = "success_reset_password_message"
  val MY_ACCOUNT_BUTTON_KEY = "my_account_button"
  val LINK_EXPIRED_TITLE_KEY = "link_expired_title"
  val LINK_EXPIRED_MESSAGE_KEY = "link_expired_message"
  val RESET_PASSWORD_BUTTON_KEY = "reset_password_button"
  val LINK_EXPIRED_BUTTON_KEY = "link_expired_button"
  val PASSWORD_RESET_KEY = "password_reset_message"
  val CONTINUE_SHOPPING_BUTTON_KEY = "continue_shopping_button"

  val REQUIRED_FIELD_ERROR = "required_field_error"
  val INVALID_ORDER_NUMBER = "invalid_order_number"
  val INVALID_FORMAT = "invalid_format"
  val NO_MATCH = "no_match"

  val ORDER_STATUS_ACTION_KEY = "order_status_action"
  val ORDER_NUMBER_LABEL_KEY = "order_number_label"
  val MORE_LABEL_KEY = "more_number_label"
  val LINK_TO_SAKSFIRST_BUTTON_LABEL_KEY = "link_saksfirst_button_label"

  val PROGRAM_DETAILS_LABEL_LINK_KEY = "program_details_link"
  val LINK_YOUR_SAKSFIRST_ACCOUNT_LABEL_KEY = "link_your_saksfirst_account_label"
  val SAKSFIRST_ACCOUNT_NUMBER_LABEL_KEY = "saksfirst_account_number_label"
  val BACK_OF_SAKS_MASTERCARD_LABEL_KEY = "back_of_saks_mastercard_label"
  val CHECK_YOUR_POINTS_LABEL_KEY = "check_your_points_label"
  val VIEW_POINTS_LABEL_KEY = "view_points_label"
  val SAKSFIRST_INFO_PART_ONE_LABEL_KEY = "saksfirst_info_part_one_label"
  val SAKSFIRST_INFO_PART_TWO_LABEL_KEY = "saksfirst_info_part_two_label"
  val ADD_YOUR_ACCOUNT_LABEL_KEY = "add_your_account_label"
  val NOT_A_MEMBER_LABEL_KEY = "not_a_member_label"
  val LEARN_MORE_LABEL_KEY = "learn_more_label"
  val SAKSFIRST_HTML_PAGELEVEL_MESSAGE = "html_page_level_message"
  val CHECK_POINTS_BUTTON_KEY = "check_points_button"
  val REDEEM_POINTS_LINK_KEY = "redeem_points_link"
  val LINK_TO_SAKSFIRST_ACTION_KEY = "link_saksfirst_action"
  val SAKSFIRST_STORE_CARD_LINK = "saksfirst_store_card_link"
  val SAKSFIRST_MASTER_CARD_LINK = "saksfirst_master_card_link"
  val ADD_PAYMENT_METHOD_ACTIION_KEY = "add_payment_action"
  val FIND_MY_SAKSFIRST_NUMBER_LABEL = "find_my_saksfirst_number_label"

  val SAKSFIRST_POINTS_LABEL = "saksfirst_points_label"
  val MEMBER_LABEL = "member_label"
  val REDEEM_POINTS_LABEL = "redeem_points_label"
  val REWARDS_DETAILS_LABEL = "rewards_details_label"
  val SAKSFIRST_STORE_CARD_LABEL = "saksfirst_store_card_label"
  val SAKSFIRST_MASTER_CARD_LABEL = "saksfirst_master_card_label"
  val PAY_YOUR_BILL_LABEL = "pay_your_bill_label"

  val ZIP_CODE_LABEL_KEY = "zip_code_label"
  val SUBMIT_BUTTON_LABEL_KEY = "submit_button"
  val EDIT_LABEL_LINK_KEY = "edit_action"
  val PAYMENT_RESOURCE_LINK_KEY = "payment_method_resource"
  val REDEMPTION_LINK_KEY = "redemption_resource"
  val DELETE_LABEL_LINK_KEY = "delete_action"
  val ADD_LABEL_LINK_KEY = "add_action"
  val ADDRESS_RESOURCE_LABEL_LINK_KEY = "address_resource"
  val ADD_LABEL_MSG_KEY = "add"
  val CHANGE_PASSWORD_LINK_KEY = "change_password_link"
  val OLD_PASSWORD_KEY = "old_password"
  val NEW_PASSWORD_KEY = "new_password"
  val CONFIRM_NEW_PASSWORD_KEY = "confirm_new_password"

  val NO_ORDER_MESSAGE_KEY = "no_order_message"
  val CHECK_BACK_MESSAGE_KEY = "check_back_message"
  val START_SHOPPING_BUTTON_KEY = "start_shopping_button"
  val PAYMENT_METHOD_TITLE_KEY = "payment_method_title"
  val BILLING_ADDRESS_TITLE_KEY = "billing_address_title"
  val GIFT_CARD_CHARGES_TITLE_KEY = "gift_card_charges_title"
  val PROMO_CODE_TITLE_KEY = "promo_code_title"
  val SUMMARY_TITLE_KEY = "summary_title"
  val SUBTOTAL_LABEL_KEY = "subtotal_label"
  val GIFT_WRAP_LABEL_KEY = "gift_wrap_label"
  val SHIPPING_HANDLING_LABEL_KEY = "shipping_handling_label"
  val TOTAL_BEFORE_TAX_LABEL_KEY = "total_before_tax_label"
  val TAX_LABEL_KEY = "tax_label"
  val TOTAL_LABEL_KEY = "total_label"
  val YOU_SAVED_LABEL_KEY = "you_saved_label"
  val BILLING_DETAILS_TITLE_KEY = "billing_details_title"
  val GIFT_CARD_LABEL_KEY = "gift_card_label"
  val GIFT_CARD_TOTAL_LABEL_KEY = "gift_card_total_label"
  val SHIPPING_TO_THIS_ADDRESS_TITLE_KEY = "shipping_to_this_address_title"
  val SHIPPING_ADDRESS_TITLE_KEY = "shipping_address_title"
  val SHIPPING_METHOD_TITLE_KEY = "shipping_method_title"
  val ITEM_NUM_TITLE_KEY = "item_num_title"
  val ITEMS_NUM_TITLE_KEY = "items_num_title"
  val STANDARD_DELIVERY_LABEL_KEY = "standard_delivery_label"
  val RUSH_DELIVERY_LABEL_KEY = "rush_delivery_label"
  val EST_DELIVERY_LABEL_KEY = "est_delivery_label"
  val EST_DELIVERY_NOT_AVAILABEL_MESSAGE_KEY = "est_delivery_not_availabel_message"
  val ELECTRONIC_DELIVERY_TITLE_KEY = "electronic_delivery_title"
  val ITEM_TITLE_KEY = "item_title"
  val UNIT_PRICE_TITLE_KEY = "unit_price_title"
  val GIFT_OPTIONS_TITLE_KEY = "gift_options_title"
  val STATUS_TITLE_KEY = "status_title"
  val SIZE_LABEL_KEY = "size_label"
  val COLOR_LABEL_KEY = "color_label"
  val QUANTITY_LABEL_KEY = "quantity_label"
  val WRITE_A_REVIEW_LINK_KEY = "write_a_review_link"
  val FINAL_SALE_MESSAGE_KEY = "final_sale_message"
  val ESTIMATED_DELIVERY_LABEL_KEY = "estimated_delivery_label"
  val TRACK_ITEM_LINK_KEY = "track_item_link"
  val GIFT_MESSAGE_LABEL_KEY = "gift_message_label"
  val FROM_LABEL_KEY = "from_label"
  val TO_LABEL_KEY = "to_label"
  val VIA_EMAIL_LABEL_KEY = "via_email_label"
  val PRINT_RECEIPT_LABEL_KEY = "print_receipt_label"
  val QUESTION_ABOUT_ORDER_MESSAGE_KEY = "question_about_order_message"
  val VIEW_MORE_ORDERS_BUTTON_KEY = "view_more_orders_button"
  val VIEW_ALL_ORDERS_LINK_KEY = "view_all_orders_link"
  val VIEW_MORE_ORDERS_ACTION = "view_more_action"
  val CANCEL_ORDER_ACTION = "cancel_order_action"
  val PAYPAL_LABEL_KEY = "paypal_label"
  val ORDER_TITLE = "order_title"
  val ORDER_LABEL = "order_label"
  val NOT_AVAILABLE_MESSSGE = "not_available_message"
  val SHIPS_FROM_STORE_MESSAGE = "ships_from_store_message"
  val SHIPS_FROM_VENDOR_MESSAGE = "ships_from_vendor_message"
  val TOOL_TIP_MESSAGE = "tool_tip_message"
  val STORE_TOOL_TIP_MESSAGE = "store_tool_tip_message"
  val DROPSHIP_TOOL_TIP_MESSAGE = "dropship_tool_tip_message"
  val PERSONALIZATION_LABEL = "personalization_label"
  val TEXT_LABEL = "text_label"
  val SIGNATURE_REQUIRED_MESSAGE = "signature_required_message"
  val CANCEL_ORDER_BUTTON = "cancel_order_button"
  val DROPSHIP_LABEL = "dropship_label"
  val CANCEL_ORDER_COUNTDOWN_MESSAGE = "cancel_order_countdown_message"
  val CANCEL_ORDER_TITLE = "cancel_order_title"
  val CANCEL_ORDER_MESSAGE_ONE = "cancel_order_message_one"
  val CANCEL_ORDER_MESSAGE_TWO = "cancel_order_message_two"
  val CANCEL_THIS_ORDER_BUTTON = "cancel_this_order_button"
  val ORDER_CANCELED_MESSAGE = "order_canceled_message"
  val ORDER_NOT_CANCELED_TITLE = "order_not_canceled_title"
  val ORDER_NOT_CANCELED_MESSAGE = "order_not_canceled_message"
  val CLOSE_BUTTON = "close_button"
  val ORDER_TECHNICAL_ERROR = "order_technical_error"
  val ORDER_CANCELED_TITLE = "order_canceled_title"
  val ORDER_STATUS_TITLE = "order_status_title"
  val ORIGINAL_ITEM_TOTAL_LABEL_KEY = "original_item_total_label"
  val ITEM_TOTAL_LABEL_KEY = "item_total_label"
  val PROMOTIONAL_SAVINGS_LABEL_KEY = "order_discount_label"
  val API_KEY = "api_key"
  val API_KEY_VAL = "ACCOUNT_API"
  val LATEST_EXPECTED = "latest_expected"
  val SHIP_DATE = "ship_date"
  val PRE_ORDER_MSG_SUFFIX = "pre_order_msg_suffix"
  val PRE_ORDER_MESSAGE = "pre_order_message"
  val PICKUP_IN_STORE_EMAIL_NOTIFICATION = "pickup_in_store_email_notification"
  val PICKUP_IN_STORE_LABEL = "pickup_in_store_label"
  val STORE_PICKUP_INFORMATION_LABEL = "store_pickup_information_label"
  val PICKUP_PERSON_LABEL = "pickup_person_label"

  //Address-Book
  val ADDRESS_TITLE = "address_title"
  val DEFAULT_ADDRESS_TYPE_LABEL = "default_address_type_label"
  val DEFAULT_SHIPPING = "default_shipping_address_label"
  val DEFAULT_BILLING = "default_billing_address_label"
  val EDIT_LABEL = "edit_label"
  val DELETE_LABEL = "delete_label"
  val ADD_ADDRESS_TITLE = "add_address_title"
  val EDIT_ADDRESS_TITLE = "edit_address_title"
  val DELETE_ADDRESS_TITLE = "delete_address_title"
  val DELETE_ADDRESS_MESSAGE = "delete_address_message"
  val CONFIRM_ADDRESS_TITLE = "confirm_address_title"
  val CONFIRM_ADDRESS_MESSAGE = "confirm_address_message"
  val ENTERED_ADDRESS_SUB_TITLE = "entered_address_sub_title"
  val ENTERED_ADDRESS_BUTTON = "entered_address_button"
  val SUGGESTED_ADDRESS_SUB_TITLE = "suggested_address_sub_title"
  val SUGGESTED_ADDRESS_BUTTON = "suggested_address_button"
  val STREET_NUMBER_SUB_TITLE = "street_number_sub_title"
  val STREET_NUMBER_LABEL = "street_number_label"
  val POTENTIAL_MATCH_LINK = "potential_match_link"
  val POTENTIAL_MATCH_TITLE = "potential_match_title"
  val POTENTIAL_MATCH_LABEL = "potential_match_label"
  val COMPANY_LABEL = "company_label"
  val ADDRESS_1_LABEL = "address_1_label"
  val ADDRESS_2_LABEL = "address_2_label"
  val CITY_LABEL = "city_label"
  val STATE_PROVINCE_LABEL = "state_province_label"
  val REGION_PROVINCE_LABEL = "region_province_label"
  val PHONE_NUMBER_LABEL = "phone_number_label"
  val CANCEL_LINK = "cancel_link"
  val SUBMIT_BUTTON = "submit_button"
  val DELETE_BUTTON = "delete_button"
  val OPTIONAL_LABEL = "optional_label"
  val VIEW_MORE_BUTTON = "view_more_button"

  val ADDRESS_ID = "id"
  val ADDRESS_TYPE = "address_type"

  val CREATE_BUTTON_KEY = "create_button"

  val SECONDARY_MAILING_ADDRESS_ERROR_KEY = "secondary_mailing_address_error"

  // Display Register Account Form
  val CREATE_ACCOUNT_PAGE_LEVEL_MESSAGE_KEY = "html_page_level_message"
  val EMAIL_LABEL_KEY = "email_label"
  val PASSWORD_LABEL_KEY = "password_label"
  val PHONE_NUMBER_LABEL_KEY = "phone_number_label"
  val POSTAL_CODE_LABEL_KEY = "postal_code_label"
  val OPTONAL_LABEL_KEY = "optional_label"
  val CANADIAN_CUSTOMER_QUESTION_KEY = "canadian_customer_question"
  val TERMS_CONDITION_LINK_KEY = "terms_and_condition_link"
  val TERMS_CONDITION_LINK = "terms_condition_url"
  val REWARDS_URL = "rewards_url"
  val CONTACT_US_LINK = "contact_us_url"
  val STORE_CARD_URL = "store_card_url"
  val MASTERCARD_URL = "mastercard_url"
  val SIGN_IN_LINK = "sign-in-url"
  val SUBMIT_ACCOUNT_BUTTON_KEY = "submit_button"
  val EMAIL_SUBSCRIPTIONS_KEY = "email_subscriptions_label"
  val CANADIAN_TERMS_OF_SERVICE_KEY = "canadian_customer_terms_of_service"
  val HTML_CANADIAN_PRIVACY_POLICY_KEY = "html_canadian_customer_privacy_policy"
  val EDIT_MESSAGE_BLOCK = "edit_message_block"
  val VALIDATION_EMAIL_KEY = "invalid_email"
  val VALIDATION_EQUAL_PWD_KEY = "invalid_equal_password"
  val VALIDATION_PASSWORD_KEY = "invalid_password"
  val VALIDATION_PWD_NOT_MATCH_KEY = "password_not_match"
  val VALIDATION_PHONE_NUMBER_KEY = "invalid_phone_number"
  val VALIDATION_REQUIRED_FIELD_KEY = "required_field"
  val REGISTER_ACTION_KEY = "register_action"
  val CREATE_ACCOUNT_KEY = "create_account"
  val FIRST_MESSAGE_KEY = "first_message"
  val SECOND_MESSAGE_KEY = "second_message"

  val SaksFifthAvenue = "SaksFifthAvenue"
  val SaksOffFifth = "SaksOffFifth"
  val SaksOffFifth_VALUE = "Saks OFF 5TH"
  val Gilt_VALUE = "Gilt (part of the Saks OFF 5TH family)"
  val SaksFifthAvenue_VALUE = "Saks Fifth Avenue"
  val Off5th_CANADA_VALUE = "Saks OFF 5TH Canada"
  val SaksFifthAvenue_CANADA_VALUE = "Saks Fifth Avenue Canada"
  val LordAndTaylor_VALUE = "Lord and Taylor"

  val SaksOptStatus = "saks_opt_status"
  val Off5thOptStatus = "off5th_opt_status"
  val GiltOptStatus = "gilt_opt_status"
  val SaksCanadaOptStatus = "saks_canada_opt_status"
  val Off5thCanadaOptStatus = "off5th_canada_opt_status"
  val LordAndTaylorOptStatus = "lord_and_taylor_opt_status"

  //SaksFirst
  val POINTS_AVAILABLE_LABEL_KEY = "points_available_label"
  val TIER_STATUS_LABEL_KEY = "tier_status_label"
  val TIER_STATUS_HEADER_LABEL_KEY = "tier_status_header_label"
  val BANNER_TITLE_LABEL_KEY = "banner_title_label"
  val BANNER_LINK_LABEL_KEY = "banner_link_label"
  val SAKS_FIRST_LANDING_PAGE_KEY = "landing_page"
  val SAKS_FIRST_POINTS_PAGE_KEY = "points_page"
  val GET_GIFT_CARD_LABEL_KEY = "get_gift_card_label"
  val CURRENT_POINT_BALANCE_LABEL_KEY = "current_point_balance_label"
  val POINTS_TO_NEXT_REWARD_LABEL_KEY = "points_to_next_reward_label"
  val AVAILABLE_GIFT_CARD_LABEL = "available_gift_card_label"
  val REWARDS_SUMMARY_LABEL = "rewards_summary_label"
  val EARN_POINTS_AND_REWARDS = "earn_points_and_rewards_msg"
  val MANAGE_POINTS_ONLINE = "manage_points_online_msg"
  val TOTAL_ORDER_POINTS_KEY = "total_order_points_msg"

  val AVAILABLE_NOW = "available_now"
  val REDEEM_TITLE = "redeem_title"
  val REDEEM = "redeem"
  val TIER_MEMBER = "tier_member"
  val MEMBER_STATUS = "member_status"
  val YOUR_POINTS = "your_points"
  val BACK_TO_YOUR_POINTS = "back_to_your_points"
  val POINTS = "points"
  val NEXT_REWARD = "next_reward"
  val REDEEM_YOUR_GIFT_CARD = "redeem_your_gift_card"
  val REDEEM_YOUR_POINTS = "redeem_your_points"
  val REDEEM_FOR_GIFT_CARD = "redeem_for_gift_card"
  val RECEIVE_GIFT_CARD = "receive_gift_card"
  val VIEW = "view"
  val EMAIL_CHANGE = "email_change"
  val MAIL_CHANGE = "mail_change"
  val TIER_INFO = "tier_info"
  val GIFT_CARD_BALANCE = "gift_card_balance"
  val GIFT_CARD_HISTORY = "gift_card_history"
  val NO_GIFT_CARD_HISTORY = "no_gift_card_history"
  val EQUALS_POINTS = "equals_points"
  val BY_EMAIL = "by_email"
  val BY_MAIL = "by_mail"
  val MAILING_ADDRESS = "mailing_address"
  val YOUR_REMAINING_BALANCES = "your_remaining_balances"
  val ANNUAL_SPEND = "annual_spend"
  val SAKSFIRST_GIFT_CARD = "saks_first_gift_card"
  val SUCCESS = "success"
  val SUCCESS_EMAIL = "success_email"
  val SUCCESS_MAIL = "success_mail"
  val EMAIL_RECEIPT = "email_receipt"
  val PAY_YOUR_BILL = "pay_your_bill"
  val PROGRAM_DETAIL = "program_details"
  val EMAIL_LABEL = "email_label"
  val STORE_CARD = "store_card"
  val ELITE_MASTERCARD = "elite_mastercard"
  val NEED_HELP = "need_help"
  val SHOP_NOW = "shop_now"
  val TERMS = "terms"
  val PHONE = "phone"
  val GIFT_CARD = "gift_card"
  val BALANCE = "balance"
  val TOTAL = "total"
  val NOT_SAKSFIRST_USER_TITLE = "not_saksfirst_user_title"
  val NOT_SAKSFIRST_USER_BODY = "not_saksfirst_user_body"
  val APPLY_NOW = "apply_now"
  val APPLY_NOW_URL = "apply_now_url"
  val BEAUTY_JOIN_MESSAGE = "beauty_join_message"
  val CONGRATULATIONS = "congratulations"
  val BEAUTY_REWARDS_AVAILABLE = "beauty_rewards_available"
  val EARN_MORE_REWARDS = "earn_more_rewards"
  val SPEND_MORE = "spend_more"
  val EARN_MORE_REWARDS_BODY = "earn_more_rewards_body"
  val REDEEMED_ALL_REWARDS = "redeemed_all_rewards"
  val SHOP_BEAUTY = "shop_beauty"
  val LEARN_MORE = "beauty_learn_more"
  val VIEW_BEAUTY_REWARDS = "view_beauty_rewards"
  val BEAUTY_REWARDS_TITLE = "beauty_rewards_title"
  val BEAUTY_REWARDS_MESSAGE = "beauty_rewards_message"
  val BEAUTY_REWARDS_PS = "beauty_rewards_ps"
  val BEAUTY_AVAILABLE_REWARDS = "beauty_available_rewards"
  val BEAUTY_REDEMPTION_CODE = "beauty_redemption_code"
  val BEAUTY_PIN_NUMBER = "beauty_pin_number"
  val BEAUTY_EMAIL_DETAILS = "beauty_email_details"
  val BEAUTY_EMAIL_CONFIRMATION = "beauty_email_confirmation"
  val LEARN_MORE_URL = "beauty_url"
  val BEAUTY_TERMS = "beauty_terms"
  val SHOP_BEAUTY_URL = "shop_beauty_url"
  val SAKSFIRST_TERMS = "saksfirst_terms"
  val BEAUTY_TERMS_URL = "beauty_terms_url"
  val SAKSFIRST_TERMS_CONDITION_URL = "saksfirst_terms_url"
  val MOBILE_SAKSFIRST_TERMS_CONDITION_URL = "mobile_saksfirst_terms_url"

  // Payment
  val ACCOUNT_TITLE_KEY = "account_title"
  val DELETE_PAYMENT_TITLE_KEY = "delete_payment_title"
  val ADD_PAYMENT_TITLE_KEY = "add_payment_title"
  val EDIT_PAYMENT_TITLE_KEY = "edit_payment_title"
  val DELETE_PAYMENT_QUESTION_KEY = "delete_payment_question"
  val DEFAULT_PMT_CHECK_BOX_LABEL_KEY = "default_payment_checkbox_label"
  val DEFAULT_PMT_LABEL_KEY = "default_payment_label"
  val DELETE_PMT_METHOD_QUESTION_KEY = "delete_payment_method_question"
  val CARD_TYPE_LABEL_KEY = "card_type_label"
  val CARD_NAME_LABEL_KEY = "name_label"
  val CARD_NUMBER_LABEL_KEY = "card_number_label"
  val CREDIT_CARD_LABEL_KEY = "credit_card_label"
  val CARD_ENDING_LABEL_KEY = "card_ending_label"
  val ENDING_IN_LABEL_KEY = "ending_in_label"
  val EXP_DATE_LABEL_KEY = "exp_date_label"
  val MONTH_LABEL_KEY = "month_label"
  val YEAR_LABEL_KEY = "year_label"
  val CARD_NAME_VALIDATION_ERROR_KEY = "name_validation_error"
  val CREDIT_CARD_NUMBER_VALIDATION_ERROR_KEY = "credit_card_number_validation_error"

  //Setting, Summary error message
  val FIRST_NAME_VALIDATION_ERROR_KEY = "first_name_validation_error"
  val LAST_NAME_VALIDATION_ERROR_KEY = "last_name_validation_error"
  val EMAIL_VALIDATION_ERROR_KEY = "email_validation_error"
  val INCORRECT_OLD_PASSWORD_ERROR_KEY = "incorrect_old_password_error"
  val CONFIRM_PASSWORDS_NOT_MATCH_ERROR_KEY = "confirm_password_match_error"
  val PASSWORD_VALIDATION_ERROR_KEY = "password_validation_error"

  // Error Codes
  val NOT_MATCH_REGISTERED_ACCOUNT = "not_match_registered_account"
  val INVALID_SIGN_IN_MESSAGE = "invalid_sign_in_message"
  val INVALID_EMAIL_FORMAT = "invalid_email_format"
  val SAKS_FIRST_LINKING_ERROR = "saks_first_linking_error"
  val INVALID_PASSWORD_FORMAT = "current_password_is_incorrect"
  val DUPLICATE_ADDRESS = "DUPLICATE_ADDRESS"
  val DUPLICATE_CARD_NUM = "duplicate_card_num"
  val INVALID_CREDIT_CARD_NUM = "invalid_credit_card_number"
  val INVALID_CREDIT_CARD = "invalid_credit_card"
  val ERROR_INVALID_ORDER_NUMBER = "ERROR_INVALID_ORDER_NUMBER"
  val SHIP_ADDRESS_INV_DAY_PHONE = "SHIP_ADDRESS_INV_DAY_PHONE"
  val BILL_ADDRESS_INV_DAY_PHONE = "BILL_ADDRESS_INV_DAY_PHONE"
  val ERROR_INVALID_BILLING_ZIP_CODE = "ERROR_INVALID_BILLING_ZIP_CODE"
  val ERROR_EMAIL_ALREADY_EXISTS = "invalid_user_id"
  val INVALID_PHONE_NUMBER = "phone_number_validation_error"
  val INVALID_FORMAT_ERROR = "invalid_format_error"
  val ERROR_INVALID_RESET_LINK_EXPIRED = "reset_link_expired"
  val ERROR_INVALID_REDEMPTION = "redemption_error"
  val LOCKED_USER_ACCOUNT = "locked_user_account"
  val EXPIRED_USER_ACCOUNT = "expired_user_account"
  val SERVER_ERROR = "blue_martini.server_error"
  val MIGRATED_USER_ACCOUNT = "migrated_user_account"
  val COULD_NOT_REDEEM = "redemption_invalid"

  //Generic Error for Lower Tier Service
  val GENERIC_ERROR = "generic.error"
  val GENERIC_ERROR_MESSAGE = "Yikes! Something went wrong."

  //Error Data from backend
  val EMAIL_ALREADY_EXISTS_IN_SYSTEM = "email_already_exists_in_system"

  // Global Key Messages
  val GLOBAL_MESSAGE_ORDER_NUMBER = "global_message.".concat(ERROR_INVALID_ORDER_NUMBER)
  val GLOBAL_MESSAGE_BILLING_ZIPCODE = "global_message.".concat(ERROR_INVALID_BILLING_ZIP_CODE)
  val GLOBAL_NOT_MATCH_REGISTERED_ACCOUNT_MSG = "global_message.".concat(NOT_MATCH_REGISTERED_ACCOUNT)
  val ACCOUNT_ALREADY_EXISTS_MSG = "email.".concat(ERROR_EMAIL_ALREADY_EXISTS)
  val INVALID_PASSWORD_FORMAT_MSG = "old_password.".concat(INVALID_PASSWORD_FORMAT)
  val GLOBAL_MESSAGE_RESET_LINK_EXPIRED = "global_message.".concat(ERROR_INVALID_RESET_LINK_EXPIRED)
  val GLOBAL_MESSAGE_REDEMPTION = "global_message.".concat(ERROR_INVALID_REDEMPTION)

  // Country & address options
  val DISPLAY = "display"
  val IS_STATE = "is_state"
  val COUNTRIES = "countries"
  val STATES = "states"
  val PROVINCES = "provinces"
  val CANADA = "CA"
  val US = "US"
  val BORDER_FREE_SUPPORTED_COUNTRIES = "shipping_countries"
  val POSTAL_CODE_REQUIRED = "postal_code_required"
  val LOCALIZATION_SERVICE = "data-service.localization"
  val INTERNATIONAL_CHECKOUT_SERVICE = "data-service.international-checkout"
  val E4X_COUNTRY = "E4X_COUNTRY"
  val COUNTRY = "countryCookieName"
  // Account Summary Constants
  val ACCOUNT_SUMMARY_NUMBER_OF_ORDERS = 5

  //Toggles
  val TOGGLE_WAIT_FOR_MORE_NUMBER = "ACCOUNT_WAIT_FOR_MORE_NUMBER"
  val IS_FAVORITE_ENABLED = "IS_FAVORITE_ENABLED"
  val MIGRATING_SAKS_FIRST = "MIGRATING_SAKS_FIRST"
  val SAKS_FIRST_SUMMARY_ENABLED = "SAKS_FIRST_SUMMARY_ENABLED"
  val GILT_EMAIL_SUBSCRIPTION = "GILT_EMAIL_SUBSCRIPTION"
  val SAKS_FIRST_PAGE = "SAKS_FIRST_PAGE"
  val DISABLE_SAKS_FIRST_REDEMPTION = "DISABLE_SAKS_FIRST_REDEMPTION"
  val BEAUTY_ENABLED = "BEAUTY_ENABLED"

  val DEFAULT_FIRST_NAME = "User"
  val DEFAULT_LAST_NAME = "Account"

  val DEV_MODE = "dev-mode"

  //Gilt Subscription
  val GILT_CHANNEL = "www.gilt.com"
  val GILT_PROMOTION_ID = "coregaccountpg"
  val GILT_USER_PARTITION = 0
  val GILT_TEST_BUCKET_ID = 0

  //Cookies
  val LOYALTY_ID = "Loyalty_id"
}

object Constants extends Constants
